# Exercício 3

## Utilizando o exercício final do módulo anterior do curso como base, considere o arquivo BR_eleitorado_2016_municipio.csv que contém dados segmentados por município, estado da federação, faixas etárias e gêneros.

## 1 - Leia o arquivo em um DataFrame e a partir dele, gere um arquivo csv, ordenado por uf e cod_municipio_tse com todas as linhas do arquivo anterior, EXCETO as linhas referentes aos estados da região sudeste do país, que deverão ser exportadas em um arquivo no formato MS Excel de nome (Sudeste.xlsx) sendo cada estado em uma *sheet* com o nome do estado correspondente.

## 2 - Baseado no número de eleitores entre 35 e 44 anos gere um arquivo JSON com nome 35_44_2016_stat.json com as seguintes informações estatísticas:
- #### Média aritmética
- #### Mediana
- #### Variância
- #### Desvio Padrão

## 3 - Crie e imprima na tela um DataFrame que demonstre a prevalência entre eleitores homens e mulheres por estado.

In [151]:
import pandas as pd
import numpy as np
import csv

In [15]:
desired_width = 320
pd.set_option('display.width', desired_width)
np.set_printoptions(linewidth=desired_width)
pd.set_option('display.max_columns',20)
pd.set_option('display.max_rows', None)

In [152]:
br = pd.read_csv('BR_eleitorado_2016_municipio.csv',delimiter=';',encoding='utf8')
br.head()

   cod_municipio_tse  uf               nome_municipio  total_eleitores  f_16  f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
0              16691  RN               ESPÍRITO SANTO             6435   120   155      492      627     1482     1233     1363      579      322        62          3353           3082                  0
1              58033  RJ                     ARARUAMA            92990   193   524     4584     7704    18136    17749    23552    11185     5988      3371         49435          43407                148
2              58386  RJ                       MACUCO             7113    88   123      419      544     1533     1461     1646      776      356       166          3641           3461                 11
3               6130  AP             LARANJAL DO JARI            27718   509   707     2710     3314     7041     5643     5343     1572      660       219         13583          14135                  0
4              91219  MT  NOSSA SENHORA DO LIVRAMENTO            11492   111   145      606      975     2433     2229     2754     1377      661       201          5343           6149                  0

In [153]:
br.sort_values(['uf','cod_municipio_tse'],inplace=True)
br.head()

      cod_municipio_tse  uf        nome_municipio  total_eleitores  f_16  f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
4546               1007  AC                BUJARI             7888   116   178      669      826     1898     1666     1543      649      285        58          3833           4055                  0
1914               1015  AC              CAPIXABA             7882   129   230      641      815     1688     1615     1736      618      288       122          3643           4239                  0
2788               1023  AC            PORTO ACRE            11331   170   315      966     1127     2490     2296     2461     1024      397        84          5498           5833                  0
3127               1031  AC   SANTA ROSA DO PURUS             3157    61   101      301      408      880      580      465      189       85        86          1563           1594                  0
3218               1040  AC  MARECHAL THAUMATURGO             9458   191   293     1050     1272     2579     1761     1367      471      287       184          4386           5072                  0

In [154]:
br = br.set_index('uf')
br.head()

    cod_municipio_tse        nome_municipio  total_eleitores  f_16  f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
uf
AC               1007                BUJARI             7888   116   178      669      826     1898     1666     1543      649      285        58          3833           4055                  0
AC               1015              CAPIXABA             7882   129   230      641      815     1688     1615     1736      618      288       122          3643           4239                  0
AC               1023            PORTO ACRE            11331   170   315      966     1127     2490     2296     2461     1024      397        84          5498           5833                  0
AC               1031   SANTA ROSA DO PURUS             3157    61   101      301      408      880      580      465      189       85        86          1563           1594                  0
AC               1040  MARECHAL THAUMATURGO             9458   191   293     1050     1272     2579     1761     1367      471      287       184          4386           5072                  0

In [155]:
ex = br.drop(['ES','MG','RJ','SP'])
len(ex)

3900

In [156]:
ex.to_csv('Exceto_Sudeste.csv',sep=';',encoding='utf8',quoting=csv.QUOTE_NONE)

In [157]:
xls = ex[ex.index != 'AC']
xls.head()

    cod_municipio_tse      nome_municipio  total_eleitores  f_16  f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
uf
AL              27006          PARIPUEIRA             9439   127   219      762     1011     2216     2093     1893      810      249        59          4891           4548                  0
AL              27014         ÁGUA BRANCA            14518   216   331     1296     1566     3364     2610     2817     1264      828       225          7469           7049                  0
AL              27022           PARICONHA             7954   175   195      699      841     1824     1468     1488      728      440        95          4063           3891                  0
AL              27030              ANADIA            12558   149   275      917     1285     2780     2376     2718     1176      623       259          6595           5963                  0
AL              27049  ESTRELA DE ALAGOAS            11658   175   227      797     1126     2502     2238     2434     1309      660       187          6179           5479                  0

In [187]:
only_sud = br.loc[['ES','MG','RJ','SP']]
only_sud

    cod_municipio_tse                  nome_municipio  total_eleitores   f_16   f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
uf
ES              56006           SÃO DOMINGOS DO NORTE             6802     64     97      383      532     1462     1345     1816      751      283        69          3288           3514                  0
ES              56014                  AFONSO CLÁUDIO            25278     86    172     1102     1876     5263     5230     6117     2822     1625       984         12757          12508                 13
ES              56022              ÁGUA DOCE DO NORTE             9635    153    212      653      775     1938     1925     2394     1032      429       124          4884           4751                  0
ES              56030                          ALEGRE            22601    131    265     1251     1866     4677     4132     5618     2649     1373       637         11676          10925                  0
ES              56049                           IRUPI            10671    170    210      666      866     2495     2311     2254      963      466       270          5216           5451                  4
ES              56057                  ALFREDO CHAVES            11969    108    110      565      857     2297     2334     3024     1425      743       506          5895           6061                 13
ES              56065                   ALTO RIO NOVO             6310     76    105      348      508     1382     1285     1437      664      335       170          3201           3106                  3
ES              56073                        ANCHIETA            23315    169    290     1260     1872     5343     4904     5570     2292     1056       559         11748          11550                 17
ES              56081                      VILA PAVÃO             6772     39     95      352      559     1470     1436     1754      653      285       128          3328           3444                  0
ES              56090                          APIACÁ             6021     37     76      312      474     1165     1151     1492      735      377       202          3065           2956                  0
ES              56103               MARECHAL FLORIANO            11410     36    124      664      922     2545     2539     2978     1181      359        62          5732           5678                  0
ES              56111                         ARACRUZ            67589    265    608     4112     6287    16506    14491    15663     5951     2401      1301         34088          33422                 79
ES              56120                      MARATAÍZES            27783    206    304     1445     2179     5888     5512     6728     3082     1558       881         14498          13281                  4
ES              56138                 ATÍLIO VIVÁCQUA             8837     49    105      439      637     1897     1676     2244      967      501       322          4343           4486                  8
ES              56146                       BREJETUBA             9605     60    138      569      792     2293     2173     2153      797      389       240          4549           5052                  4
ES              56154                    BAIXO GUANDU            22058    118    216     1264     1865     4506     4569     5875     2471      993       179         11446          10612                  0
ES              56162              SÃO ROQUE DO CANAÃ             8728     59    108      498      736     1810     1751     2417      997      306        46          4276           4452                  0
ES              56170          BARRA DE SÃO FRANCISCO            33842    184    357     1864     2687     7150     6656     8081     3469     2004      1387         17448          16365                 29
ES              56189                       SOORETAMA            18868    136    246     1127     1847     4646     4222     4087     1462      709       384          9452           9407                  9
ES              56197                   BOA ESPERANÇA             9973     52    110      561      890     2125     2050     2607     1053      437        88          5106           4867                  0
ES              56200                      PONTO BELO             6046     99    120      357      418     1139     1181     1531      698      351       152          3003           3043                  0
ES              56219              BOM JESUS DO NORTE             6926     51     84      395      544     1321     1345     1865      842      365       113          3637           3289                  0
ES              56227                    VILA VALÉRIO            11606    128    230      668      973     2656     2480     2855     1108      394       114          5636           5970                  0
ES              56235         CACHOEIRO DE ITAPEMIRIM           136943    298    824     6595    11132    29844    26859    35322    14887     6943      4233         72446          64353                144
ES              56251                       CARIACICA           255477    303    905    13020    22148    60123    54098    63348    24821    10727      5975        135276         120029                172
ES              56278                         CASTELO            28155     74    185     1229     2073     6051     5482     7403     3055     1768       834         14370          13785                  0
ES              56294                        COLATINA            88039    168    475     4178     6585    18848    17565    23166     9370     4682      3002         46347          41640                 52
ES              56308           GOVERNADOR LINDENBERG             8956     49     88      365      662     1856     1799     2342      966      508       321          4384           4567                  5
ES              56316              CONCEIÇÃO DA BARRA            23132    202    326     1449     2129     5263     4679     5265     2110     1053       654         11769          11358                  5
ES              56332            CONCEIÇÃO DO CASTELO             9449     32     78      458      688     2134     1899     2302     1041      495       322          4750           4695                  4
ES              56359          DIVINO DE SÃO LOURENÇO             3681     53     78      241      305      816      657      904      388      180        59          1753           1928                  0
ES              56375                DOMINGOS MARTINS            25739     94    216     1417     2068     5721     5639     6774     2669      968       173         12751          12988                  0
ES              56391              DORES DO RIO PRETO             5700     46     92      348      529     1287     1090     1417      567      238        86          2794           2906                  0
ES              56413                      ECOPORANGA            19167    239    301     1133     1567     3934     3910     4543     2060     1026       453          9626           9532                  9
ES              56430                          FUNDÃO            14423    127    194      805     1046     3028     2920     3559     1590      715       438          7197           7200                 26
ES              56456                          GUAÇUÍ            21752     90    181      993     1723     4556     4177     5194     2541     1291      1006         11431          10306                 15
ES              56472                       GUARAPARI            88239    212    511     4693     7274    19245    18495    21814     9127     4342      2524         45363          42812                 64
ES              56499                         IBIRAÇU             9088     44     84      528      803     2023     1835     2204      964      441       161          4680           4408                  0
ES              56502                       IBITIRAMA             6251     54    101      415      534     1416     1303     1554      635      197        42          3091           3160                  0
ES              56510                          ICONHA            10957     81    134      531      877     2301     2149     2830     1188      608       258          5424           5531                  2
ES              56537                        ITAGUAÇU            10982     68    126      497      765     2162     2097     2981     1419      652       215          5439           5543                  0
ES              56553                      ITAPEMIRIM            27813    293    488     1812     2361     6070     5723     6576     2895     1180       414         14464          13349                  0
ES              56570                         ITARANA             9074    116    102      474      697     1813     1772     2345     1087      518       150          4480           4594                  0
ES              56596                            IÚNA            21092    143    234     1097     1614     4681     4243     5095     2094     1116       775         10606          10471                 15
ES              56618               JERÔNIMO MONTEIRO             9768     53    105      563      837     2024     1770     2440     1109      605       262          4990           4774                  4
ES              56626                      JOÃO NEIVA            12162     35    111      564      918     2468     2432     3149     1427      679       378          6253           5909                  0
ES              56634                        LINHARES           110140    354    825     6122     9843    26441    23836    25499    10020     4685      2513         56570          53397                173
ES              56650                    MANTENÓPOLIS            11056    121    140      676      913     2279     2136     2699     1172      683       236          5561           5489                  6
ES              56677                   MIMOSO DO SUL            18280     90    257     1035     1378     3678     3540     5052     2237      800       213          9219           9061                  0
ES              56693                        MONTANHA            14662    109    186      805     1292     3115     2859     3514     1470      899       413          7511           7116                 35
ES              56715                        MUCURICI             4851     68    114      318      399     1043      888     1201      506      259        55          2420           2431                  0
ES              56731                    MUNIZ FREIRE            13759    100    145      851     1162     2944     2719     3323     1425      747       343          6888           6871                  0
ES              56758                           MUQUI            11095     61     99      560      878     2427     2046     2798     1247      677       300          5541           5551                  3
ES              56774                    NOVA VENÉCIA            37855    135    308     2078     3250     8166     7473     9369     3785     1973      1317         19345          18491                 19
ES              56790                          PANCAS            16536    117    201      874     1270     3392     3241     3979     1826      965       669          8294           8230                 12
ES              56812                       PINHEIROS            17714    152    253      953     1473     4074     3629     4123     1750      957       350          9190           8506                 18
ES              56839                           PIÚMA            16085    147    241      982     1434     3396     3180     3869     1561      815       460          8228           7848                  9
ES              56855              PRESIDENTE KENNEDY            12270    151    214      786     1103     2869     2445     2792     1154      553       200          6057           6201                 12
ES              56871                 RIO NOVO DO SUL             8598     51     76      453      658     1829     1684     2155     1015      474       203          4294           4304                  0
ES              56898                SANTA LEOPOLDINA             9810     79    102      529      729     2056     1959     2551     1130      471       204          4642           5168                  0
ES              56910                    SANTA TERESA            18363     61    155      948     1380     4047     3566     4910     2223      871       202          9114           9249                  0
ES              56936            SÃO GABRIEL DA PALHA            25445    101    239     1172     1911     5747     5411     6177     2557     1265       864         13198          12233                 14
ES              56952             SÃO JOSÉ DO CALÇADO             9328     57     84      473      741     1765     1647     2420     1192      638       310          4668           4652                  8
ES              56979                      SÃO MATEUS            80238    234    555     4280     7348    18636    17003    19373     7355     3342      2111         41238          38937                 63
ES              56995                           SERRA           308151    621   1757    17688    28123    76409    67748    73223    27686    10170      4717        162272         145744                135
ES              57010                           VIANA            45920    141    376     2689     4237    11394     9947    11138     4275     1429       294         23818          22102                  0
ES              57037                      VILA VELHA           316619    364   1196    15425    25160    69261    65007    81738    33884    15535      9039        170286         146064                269
ES              57053                         VITÓRIA           232829    479   1313    12867    17501    50915    47244    61236    28214    10053      3005        127968         104861                  0
ES              57070                      MARILÂNDIA             9230     46    102      528      707     1909     1849     2630     1014      360        85          4643           4587                  0
ES              57096                         IBATIBA            18133    156    268     1059     1451     4120     3838     4036     1754      897       554          9137           8986                 10
ES              57118                     RIO BANANAL            15199     79    161      769     1214     3354     3103     3775     1473      741       529          7357           7826                 16
ES              57134                         JAGUARÉ            20691    122    213     1164     1803     5317     4381     4619     1781      811       480         10299          10383                  9
ES              57150                   PEDRO CANÁRIO            18144    169    260     1184     1704     4168     3681     4088     1612      819       457          9168           8970                  6
ES              57916                LARANJA DA TERRA             8254     55     96      411      600     1583     1701     2343      999      409        57          4027           4227                  0
ES              57932           SANTA MARIA DE JETIBÁ            27940    114    266     1532     2535     6950     5952     6137     2514     1264       676         13804          14118                 18
ES              57959                     VARGEM ALTA            15385     78    155      808     1175     3315     3106     4001     1540      721       485          7513           7859                 13
ES              57975         VENDA NOVA DO IMIGRANTE            17611     48    135      911     1508     4067     3707     4413     1574      839       409          8932           8672                  7
ES              57991                    ÁGUIA BRANCA             7496     99    133      459      577     1589     1453     1946      790      355        95          3702           3794                  0
MG              40002             ALFREDO VASCONCELOS             5441     45     57      294      466     1073     1099     1406      546      299       156          2704           2733                  4
MG              40010             ABADIA DOS DOURADOS             5844     67     84      294      388     1010     1073     1559      785      442       142          2846           2997                  1
MG              40029                         ARAPORÃ             5691     74     82      373      508     1296     1225     1290      524      243        76          2864           2827                  0
MG              40037                          ABAETÉ            18486     42    138      860     1357     3522     3300     5032     2217     1255       763          9511           8964                 11
MG              40045            BRASILÂNDIA DE MINAS            11513    112    223      817     1227     2661     2286     2485      931      478       293          5604           5898                 11
MG              40053                      ABRE CAMPO            10125     92    149      551      761     1995     1901     2528     1186      656       306          5173           4952                  0
MG              40061                 CAPITÃO ANDRADE             4239     69     62      240      374      849      761     1008      465      284       127          2177           2058                  4
MG              40070                         ACAIACA             3647     25     42      186      273      721      700      886      380      256       178          1830           1797                 20
MG              40088                     CARNEIRINHO             7760     52     81      379      584     1592     1538     1970      894      468       202          3728           4032                  0
MG              40096                         AÇUCENA             8883     54    109      533      740     1744     1567     1897      932      662       645          4337           4542                  4
MG              40100                          CATUJI             7852    129    190      564      837     1946     1486     1513      656      375       156          3958           3889                  5
MG              40118                        ÁGUA BOA            12397    231    266      855     1148     2492     2176     2665     1161      773       630          6106           6265                 26
MG              40126                   DIVISA ALEGRE             5048     47     74      340      506     1225     1007     1026      427      253       143          2570           2477                  1
MG              40134                   ÁGUA COMPRIDA             2506     28     31      121      211      455      476      633      315      162        74          1194           1311                  1
MG              40142                     DIVISÓPOLIS             6415     68    114      376      612     1424     1207     1455      625      354       180          3152           3258                  5
MG              40150                         AGUANIL             4081     44     60      222      333      795      736     1041      505      235       110          1958           2119                  4
MG              40169                         DURANDÉ             6581    114    143      434      600     1428     1213     1442      580      333       294          3222           3358                  1
MG              40177                  ÁGUAS FORMOSAS            14949    132    191      861     1351     3199     2730     3188     1501     1110       686          7574           7352                 23

In [188]:
es = br.loc['ES']
mg = br.loc['MG']
sp = br.loc['SP']
rj = br.loc['RJ']
es

    cod_municipio_tse           nome_municipio  total_eleitores  f_16  f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
uf
ES              56006    SÃO DOMINGOS DO NORTE             6802    64    97      383      532     1462     1345     1816      751      283        69          3288           3514                  0
ES              56014           AFONSO CLÁUDIO            25278    86   172     1102     1876     5263     5230     6117     2822     1625       984         12757          12508                 13
ES              56022       ÁGUA DOCE DO NORTE             9635   153   212      653      775     1938     1925     2394     1032      429       124          4884           4751                  0
ES              56030                   ALEGRE            22601   131   265     1251     1866     4677     4132     5618     2649     1373       637         11676          10925                  0
ES              56049                    IRUPI            10671   170   210      666      866     2495     2311     2254      963      466       270          5216           5451                  4
ES              56057           ALFREDO CHAVES            11969   108   110      565      857     2297     2334     3024     1425      743       506          5895           6061                 13
ES              56065            ALTO RIO NOVO             6310    76   105      348      508     1382     1285     1437      664      335       170          3201           3106                  3
ES              56073                 ANCHIETA            23315   169   290     1260     1872     5343     4904     5570     2292     1056       559         11748          11550                 17
ES              56081               VILA PAVÃO             6772    39    95      352      559     1470     1436     1754      653      285       128          3328           3444                  0
ES              56090                   APIACÁ             6021    37    76      312      474     1165     1151     1492      735      377       202          3065           2956                  0
ES              56103        MARECHAL FLORIANO            11410    36   124      664      922     2545     2539     2978     1181      359        62          5732           5678                  0
ES              56111                  ARACRUZ            67589   265   608     4112     6287    16506    14491    15663     5951     2401      1301         34088          33422                 79
ES              56120               MARATAÍZES            27783   206   304     1445     2179     5888     5512     6728     3082     1558       881         14498          13281                  4
ES              56138          ATÍLIO VIVÁCQUA             8837    49   105      439      637     1897     1676     2244      967      501       322          4343           4486                  8
ES              56146                BREJETUBA             9605    60   138      569      792     2293     2173     2153      797      389       240          4549           5052                  4
ES              56154             BAIXO GUANDU            22058   118   216     1264     1865     4506     4569     5875     2471      993       179         11446          10612                  0
ES              56162       SÃO ROQUE DO CANAÃ             8728    59   108      498      736     1810     1751     2417      997      306        46          4276           4452                  0
ES              56170   BARRA DE SÃO FRANCISCO            33842   184   357     1864     2687     7150     6656     8081     3469     2004      1387         17448          16365                 29
ES              56189                SOORETAMA            18868   136   246     1127     1847     4646     4222     4087     1462      709       384          9452           9407                  9
ES              56197            BOA ESPERANÇA             9973    52   110      561      890     2125     2050     2607     1053      437        88          5106           4867                  0
ES              56200               PONTO BELO             6046    99   120      357      418     1139     1181     1531      698      351       152          3003           3043                  0
ES              56219       BOM JESUS DO NORTE             6926    51    84      395      544     1321     1345     1865      842      365       113          3637           3289                  0
ES              56227             VILA VALÉRIO            11606   128   230      668      973     2656     2480     2855     1108      394       114          5636           5970                  0
ES              56235  CACHOEIRO DE ITAPEMIRIM           136943   298   824     6595    11132    29844    26859    35322    14887     6943      4233         72446          64353                144
ES              56251                CARIACICA           255477   303   905    13020    22148    60123    54098    63348    24821    10727      5975        135276         120029                172
ES              56278                  CASTELO            28155    74   185     1229     2073     6051     5482     7403     3055     1768       834         14370          13785                  0
ES              56294                 COLATINA            88039   168   475     4178     6585    18848    17565    23166     9370     4682      3002         46347          41640                 52
ES              56308    GOVERNADOR LINDENBERG             8956    49    88      365      662     1856     1799     2342      966      508       321          4384           4567                  5
ES              56316       CONCEIÇÃO DA BARRA            23132   202   326     1449     2129     5263     4679     5265     2110     1053       654         11769          11358                  5
ES              56332     CONCEIÇÃO DO CASTELO             9449    32    78      458      688     2134     1899     2302     1041      495       322          4750           4695                  4
ES              56359   DIVINO DE SÃO LOURENÇO             3681    53    78      241      305      816      657      904      388      180        59          1753           1928                  0
ES              56375         DOMINGOS MARTINS            25739    94   216     1417     2068     5721     5639     6774     2669      968       173         12751          12988                  0
ES              56391       DORES DO RIO PRETO             5700    46    92      348      529     1287     1090     1417      567      238        86          2794           2906                  0
ES              56413               ECOPORANGA            19167   239   301     1133     1567     3934     3910     4543     2060     1026       453          9626           9532                  9
ES              56430                   FUNDÃO            14423   127   194      805     1046     3028     2920     3559     1590      715       438          7197           7200                 26
ES              56456                   GUAÇUÍ            21752    90   181      993     1723     4556     4177     5194     2541     1291      1006         11431          10306                 15
ES              56472                GUARAPARI            88239   212   511     4693     7274    19245    18495    21814     9127     4342      2524         45363          42812                 64
ES              56499                  IBIRAÇU             9088    44    84      528      803     2023     1835     2204      964      441       161          4680           4408                  0
ES              56502                IBITIRAMA             6251    54   101      415      534     1416     1303     1554      635      197        42          3091           3160                  0
ES              56510                   ICONHA            10957    81   134      531      877     2301     2149     2830     1188      608       258          5424           5531                  2
ES              56537                 ITAGUAÇU            10982    68   126      497      765     2162     2097     2981     1419      652       215          5439           5543                  0
ES              56553               ITAPEMIRIM            27813   293   488     1812     2361     6070     5723     6576     2895     1180       414         14464          13349                  0
ES              56570                  ITARANA             9074   116   102      474      697     1813     1772     2345     1087      518       150          4480           4594                  0
ES              56596                     IÚNA            21092   143   234     1097     1614     4681     4243     5095     2094     1116       775         10606          10471                 15
ES              56618        JERÔNIMO MONTEIRO             9768    53   105      563      837     2024     1770     2440     1109      605       262          4990           4774                  4
ES              56626               JOÃO NEIVA            12162    35   111      564      918     2468     2432     3149     1427      679       378          6253           5909                  0
ES              56634                 LINHARES           110140   354   825     6122     9843    26441    23836    25499    10020     4685      2513         56570          53397                173
ES              56650             MANTENÓPOLIS            11056   121   140      676      913     2279     2136     2699     1172      683       236          5561           5489                  6
ES              56677            MIMOSO DO SUL            18280    90   257     1035     1378     3678     3540     5052     2237      800       213          9219           9061                  0
ES              56693                 MONTANHA            14662   109   186      805     1292     3115     2859     3514     1470      899       413          7511           7116                 35
ES              56715                 MUCURICI             4851    68   114      318      399     1043      888     1201      506      259        55          2420           2431                  0
ES              56731             MUNIZ FREIRE            13759   100   145      851     1162     2944     2719     3323     1425      747       343          6888           6871                  0
ES              56758                    MUQUI            11095    61    99      560      878     2427     2046     2798     1247      677       300          5541           5551                  3
ES              56774             NOVA VENÉCIA            37855   135   308     2078     3250     8166     7473     9369     3785     1973      1317         19345          18491                 19
ES              56790                   PANCAS            16536   117   201      874     1270     3392     3241     3979     1826      965       669          8294           8230                 12
ES              56812                PINHEIROS            17714   152   253      953     1473     4074     3629     4123     1750      957       350          9190           8506                 18
ES              56839                    PIÚMA            16085   147   241      982     1434     3396     3180     3869     1561      815       460          8228           7848                  9
ES              56855       PRESIDENTE KENNEDY            12270   151   214      786     1103     2869     2445     2792     1154      553       200          6057           6201                 12
ES              56871          RIO NOVO DO SUL             8598    51    76      453      658     1829     1684     2155     1015      474       203          4294           4304                  0
ES              56898         SANTA LEOPOLDINA             9810    79   102      529      729     2056     1959     2551     1130      471       204          4642           5168                  0
ES              56910             SANTA TERESA            18363    61   155      948     1380     4047     3566     4910     2223      871       202          9114           9249                  0
ES              56936     SÃO GABRIEL DA PALHA            25445   101   239     1172     1911     5747     5411     6177     2557     1265       864         13198          12233                 14
ES              56952      SÃO JOSÉ DO CALÇADO             9328    57    84      473      741     1765     1647     2420     1192      638       310          4668           4652                  8
ES              56979               SÃO MATEUS            80238   234   555     4280     7348    18636    17003    19373     7355     3342      2111         41238          38937                 63
ES              56995                    SERRA           308151   621  1757    17688    28123    76409    67748    73223    27686    10170      4717        162272         145744                135
ES              57010                    VIANA            45920   141   376     2689     4237    11394     9947    11138     4275     1429       294         23818          22102                  0
ES              57037               VILA VELHA           316619   364  1196    15425    25160    69261    65007    81738    33884    15535      9039        170286         146064                269
ES              57053                  VITÓRIA           232829   479  1313    12867    17501    50915    47244    61236    28214    10053      3005        127968         104861                  0
ES              57070               MARILÂNDIA             9230    46   102      528      707     1909     1849     2630     1014      360        85          4643           4587                  0
ES              57096                  IBATIBA            18133   156   268     1059     1451     4120     3838     4036     1754      897       554          9137           8986                 10
ES              57118              RIO BANANAL            15199    79   161      769     1214     3354     3103     3775     1473      741       529          7357           7826                 16
ES              57134                  JAGUARÉ            20691   122   213     1164     1803     5317     4381     4619     1781      811       480         10299          10383                  9
ES              57150            PEDRO CANÁRIO            18144   169   260     1184     1704     4168     3681     4088     1612      819       457          9168           8970                  6
ES              57916         LARANJA DA TERRA             8254    55    96      411      600     1583     1701     2343      999      409        57          4027           4227                  0
ES              57932    SANTA MARIA DE JETIBÁ            27940   114   266     1532     2535     6950     5952     6137     2514     1264       676         13804          14118                 18
ES              57959              VARGEM ALTA            15385    78   155      808     1175     3315     3106     4001     1540      721       485          7513           7859                 13
ES              57975  VENDA NOVA DO IMIGRANTE            17611    48   135      911     1508     4067     3707     4413     1574      839       409          8932           8672                  7
ES              57991             ÁGUIA BRANCA             7496    99   133      459      577     1589     1453     1946      790      355        95          3702           3794                  0

In [169]:
x = br.loc[br['f_16'] == 127]
x

    cod_municipio_tse         nome_municipio  total_eleitores  f_16  f_17  f_18_20  f_21_24  f_25_34  f_35_44  f_45_59  f_60_69  f_70_79  f_sup_79  gen_feminino  gen_masculino  gen_nao_informado
uf
AL              27006             PARIPUEIRA             9439   127   219      762     1011     2216     2093     1893      810      249        59          4891           4548                  0
BA              34010                   CAEM             8580   127   189      574      828     1933     1546     1733      838      568       244          4434           4145                  1
BA              34690   CONCEIÇÃO DO JACUÍPE            23447   127   258     1302     2030     5539     5376     5288     2018     1148       361         12566          10879                  2
BA              38431                RODELAS             6692   127   143      481      622     1660     1322     1288      527      314       208          3433           3259                  0
ES              56430                 FUNDÃO            14423   127   194      805     1046     3028     2920     3559     1590      715       438          7197           7200                 26
MG              50458            PORTO FIRME             8917   127   140      520      726     1817     1701     2075      918      546       347          4458           4452                  7
MG              53597             TAIOBEIRAS            24948   127   287     1378     2224     5597     4963     5584     2440     1415       933         13074          11853                 21
MG              53970                    UBÁ            69602   127   407     3420     5372    14506    13715    18066     7543     3829      2617         36633          32906                 63
MS              90190   APARECIDA DO TABOADO            18029   127   220     1143     1643     3667     3639     4272     1891      955       472          9242           8787                  0
MT              91391                POXORÉU            13580   127   160      615      989     2455     2251     3489     1748      950       794          6278           7289                 13
PE              23000                QUIXABA             5442   127   128      442      489     1200     1016     1126      579      253        82          2774           2668                  0
PE              26093             TRACUNHAÉM            11057   127   203      660     1030     2726     2402     2371      914      497       127          5743           5305                  9
PR              74748   RIO BONITO DO IGUAÇU            10522   127   189      711     1044     2139     2029     2657     1012      451       163          5021           5499                  2
PR              74756       CAMPINA DA LAGOA            11484   127   179      721      950     1998     2057     3064     1395      730       262          5975           5509                  0
PR              79634               MATINHOS            29417   127   276     1600     2335     5438     5545     7836     3857     1715       688         15458          13953                  6
RN              16063  SÃO MIGUEL DO GOSTOSO             8015   127   172      613      878     2087     1462     1432      613      364       266          3895           4119                  1
RN              16411          CAMPO REDONDO             8168   127   135      552      749     1795     1439     1755      795      564       257          4137           4026                  5
RS              89192               SOLEDADE            23421   127   226     1275     1952     4671     4152     5848     2750     1509       911         12185          11236                  0
SP              69531               REGISTRO            45132   127   308     2612     3670     9503     9541    10819     4532     2559      1461         23276          21803                 53
SP              72370                VINHEDO            55051   127   339     2865     4226    12259    11913    14104     5806     2500       912         28763          26287                  1
TO              92193                 ANANÁS             7349   127   150      514      729     1638     1324     1461      613      437       356          3639           3710                  0

In [193]:
writer = pd.ExcelWriter('Sudeste.xlsx')
es.to_excel(writer,'ES')
mg.to_excel(writer,'MG')
sp.to_excel(writer,'SP')
rj.to_excel(writer,'RJ')
writer.save()