# Exercício 2

## Utilizando o exercício 1 da Lista de Exercícios 2, considere um arquivo de entrada no formato CSV (comma separated values) com informações relativas a acidentes na aviação civil brasileira nos últimos 10 anos (arquivo anv.csv)

### 1- Crie uma função que efetue a leitura do arquivo e processe seus dados identificando o total de ocorrencias no período avaliado e, baseado nessa informação criar um arquivo de saída em formato JSON (statistics.json) com as seguintes as estatísticas (número de ocorrências e percentual do total) por fase de operação (coluna aeronave_fase_operacao)

### 2 - Crie um arquivo de saida (formato CSV, encoding UTF-8 e separador ;) com nome levels.csv contendo as seguintes informações:
```
operation          -> aeronave_operador_categoria
type               -> aeronave_tipo_veiculo
manufacturer       -> aeronave_fabricante
engine_type        -> aeronave_motor_tipo
engines            -> aeronave_motor_quantidade
year_manufacturing -> aeronave_ano_fabricacao
seating            -> aeronave_assentos
fatalities         -> total_fatalidades
```

### Considerando apenas acidentes cujo nível de dano da aeronave tenha sido  LEVE ou NENHUM (coluna aeronave_nivel_dano) E que o número de fatalidades (total_fatalidades) tenha sido superior à 0 (zero), ordenados por operation, type e manufacturer.

In [1]:
import pandas as pd

### Lendo arquivo CSV

In [3]:
anv = pd.read_csv('anv.csv', encoding='utf-8', delimiter='~', quotechar='"')

### Extraindo Estatísticas

In [12]:
s1 = anv['aeronave_fase_operacao'].value_counts()
s1

POUSO                              914
DECOLAGEM                          795
CRUZEIRO                           660
CORRIDA APÓS POUSO                 602
TÁXI                               439
SUBIDA                             359
APROXIMAÇÃO FINAL                  234
DESCIDA                            192
ESPECIALIZADA                      173
MANOBRA                            161
CIRCUITO DE TRÁFEGO                125
OUTRA FASE                         101
ESTACIONAMENTO                      72
INDETERMINADA                       71
NAVEGAÇÃO A BAIXA ALTURA            60
OPERAÇÃO DE SOLO                    46
ARREMETIDA NO SOLO                  42
PARTIDA DO MOTOR                    30
ARREMETIDA NO AR                    25
PAIRADO                             20
RETA FINAL                          16
CHEQUE DE MOTOR OU ROTOR            13
DECOLAGEM VERTICAL                   8
PROCEDIMENTO DE APROXIMAÇÃO IFR      7
SAÍDA IFR                            7
PUSHBACK                             6
ESPERA                               4
DESCIDA DESCONTROLADA                2
DESCIDA DE EMERGÊNCIA                2
***                                  1
EMPREGO MILITAR                      1
Name: aeronave_fase_operacao, dtype: int64

In [13]:
s2 = anv['aeronave_fase_operacao'].value_counts(normalize=True) * 100
s2

POUSO                              17.617579
DECOLAGEM                          15.323824
CRUZEIRO                           12.721665
CORRIDA APÓS POUSO                 11.603701
TÁXI                                8.461835
SUBIDA                              6.919815
APROXIMAÇÃO FINAL                   4.510409
DESCIDA                             3.700848
ESPECIALIZADA                       3.334618
MANOBRA                             3.103315
CIRCUITO DE TRÁFEGO                 2.409406
OUTRA FASE                          1.946800
ESTACIONAMENTO                      1.387818
INDETERMINADA                       1.368543
NAVEGAÇÃO A BAIXA ALTURA            1.156515
OPERAÇÃO DE SOLO                    0.886662
ARREMETIDA NO SOLO                  0.809561
PARTIDA DO MOTOR                    0.578258
ARREMETIDA NO AR                    0.481881
PAIRADO                             0.385505
RETA FINAL                          0.308404
CHEQUE DE MOTOR OU ROTOR            0.250578
DECOLAGEM VERTICAL                  0.154202
PROCEDIMENTO DE APROXIMAÇÃO IFR     0.134927
SAÍDA IFR                           0.134927
PUSHBACK                            0.115652
ESPERA                              0.077101
DESCIDA DESCONTROLADA               0.038551
DESCIDA DE EMERGÊNCIA               0.038551
***                                 0.019275
EMPREGO MILITAR                     0.019275
Name: aeronave_fase_operacao, dtype: float64

In [14]:
stats = pd.concat([s1, s2], axis=1, keys=['ocorrências', 'percentual'])
stats

                                 ocorrências  percentual
POUSO                                    914   17.617579
DECOLAGEM                                795   15.323824
CRUZEIRO                                 660   12.721665
CORRIDA APÓS POUSO                       602   11.603701
TÁXI                                     439    8.461835
SUBIDA                                   359    6.919815
APROXIMAÇÃO FINAL                        234    4.510409
DESCIDA                                  192    3.700848
ESPECIALIZADA                            173    3.334618
MANOBRA                                  161    3.103315
CIRCUITO DE TRÁFEGO                      125    2.409406
OUTRA FASE                               101    1.946800
ESTACIONAMENTO                            72    1.387818
INDETERMINADA                             71    1.368543
NAVEGAÇÃO A BAIXA ALTURA                  60    1.156515
OPERAÇÃO DE SOLO                          46    0.886662
ARREMETIDA NO SOLO                        42    0.809561
PARTIDA DO MOTOR                          30    0.578258
ARREMETIDA NO AR                          25    0.481881
PAIRADO                                   20    0.385505
RETA FINAL                                16    0.308404
CHEQUE DE MOTOR OU ROTOR                  13    0.250578
DECOLAGEM VERTICAL                         8    0.154202
PROCEDIMENTO DE APROXIMAÇÃO IFR            7    0.134927
SAÍDA IFR                                  7    0.134927
PUSHBACK                                   6    0.115652
ESPERA                                     4    0.077101
DESCIDA DESCONTROLADA                      2    0.038551
DESCIDA DE EMERGÊNCIA                      2    0.038551
***                                        1    0.019275
EMPREGO MILITAR                            1    0.019275

In [15]:
stats.reset_index(inplace=True)
stats

                              index  ocorrências  percentual
0                             POUSO          914   17.617579
1                         DECOLAGEM          795   15.323824
2                          CRUZEIRO          660   12.721665
3                CORRIDA APÓS POUSO          602   11.603701
4                              TÁXI          439    8.461835
5                            SUBIDA          359    6.919815
6                 APROXIMAÇÃO FINAL          234    4.510409
7                           DESCIDA          192    3.700848
8                     ESPECIALIZADA          173    3.334618
9                           MANOBRA          161    3.103315
10              CIRCUITO DE TRÁFEGO          125    2.409406
11                       OUTRA FASE          101    1.946800
12                   ESTACIONAMENTO           72    1.387818
13                    INDETERMINADA           71    1.368543
14         NAVEGAÇÃO A BAIXA ALTURA           60    1.156515
15                 OPERAÇÃO DE SOLO           46    0.886662
16               ARREMETIDA NO SOLO           42    0.809561
17                 PARTIDA DO MOTOR           30    0.578258
18                 ARREMETIDA NO AR           25    0.481881
19                          PAIRADO           20    0.385505
20                       RETA FINAL           16    0.308404
21         CHEQUE DE MOTOR OU ROTOR           13    0.250578
22               DECOLAGEM VERTICAL            8    0.154202
23  PROCEDIMENTO DE APROXIMAÇÃO IFR            7    0.134927
24                        SAÍDA IFR            7    0.134927
25                         PUSHBACK            6    0.115652
26                           ESPERA            4    0.077101
27            DESCIDA DESCONTROLADA            2    0.038551
28            DESCIDA DE EMERGÊNCIA            2    0.038551
29                              ***            1    0.019275
30                  EMPREGO MILITAR            1    0.019275

In [10]:
stats.rename(columns={'index': 'fase_operação'}, inplace=True)
stats

                      fase_operação  ocorrências  percentual
0                             POUSO          914   17.617579
1                         DECOLAGEM          795   15.323824
2                          CRUZEIRO          660   12.721665
3                CORRIDA APÓS POUSO          602   11.603701
4                              TÁXI          439    8.461835
5                            SUBIDA          359    6.919815
6                 APROXIMAÇÃO FINAL          234    4.510409
7                           DESCIDA          192    3.700848
8                     ESPECIALIZADA          173    3.334618
9                           MANOBRA          161    3.103315
10              CIRCUITO DE TRÁFEGO          125    2.409406
11                       OUTRA FASE          101    1.946800
12                   ESTACIONAMENTO           72    1.387818
13                    INDETERMINADA           71    1.368543
14         NAVEGAÇÃO A BAIXA ALTURA           60    1.156515
15                 OPERAÇÃO DE SOLO           46    0.886662
16               ARREMETIDA NO SOLO           42    0.809561
17                 PARTIDA DO MOTOR           30    0.578258
18                 ARREMETIDA NO AR           25    0.481881
19                          PAIRADO           20    0.385505
20                       RETA FINAL           16    0.308404
21         CHEQUE DE MOTOR OU ROTOR           13    0.250578
22               DECOLAGEM VERTICAL            8    0.154202
23  PROCEDIMENTO DE APROXIMAÇÃO IFR            7    0.134927
24                        SAÍDA IFR            7    0.134927
25                         PUSHBACK            6    0.115652
26                           ESPERA            4    0.077101
27            DESCIDA DESCONTROLADA            2    0.038551
28            DESCIDA DE EMERGÊNCIA            2    0.038551
29                              ***            1    0.019275
30                  EMPREGO MILITAR            1    0.019275

### Gravando Json

In [9]:
with open('/temp/statistics.json', 'w', encoding='utf-8') as file:
    stats.to_json(file, orient='records', force_ascii=False)

FileNotFoundError: [Errno 2] No such file or directory: '/temp/statistics.json'

### Fatiando o DataFrame de acordo com os critérios

In [ ]:
c1 = anv['total_fatalidades'] > 0
c2 = anv['aeronave_nivel_dano'] == 'LEVE'
c3 = anv['aeronave_nivel_dano'] == 'NENHUM'
levels = anv[(c1 & (c2 | c3))]

### Obtendo apenas as colunas que deverão ser gravadas no arquivo

In [38]:
levels = levels[['aeronave_operador_categoria', 'aeronave_tipo_veiculo', 'aeronave_fabricante',
                 'aeronave_motor_tipo', 'aeronave_motor_quantidade', 'aeronave_ano_fabricacao',
                 'aeronave_assentos', 'total_fatalidades']]

### Renomeando as colunas

In [39]:
levels.rename(columns={'aeronave_operador_categoria' : 'operation',
                       'aeronave_tipo_veiculo' : 'type',
                       'aeronave_fabricante' : 'manufacturer',
                       'aeronave_motor_tipo' : 'engine_type',
                       'aeronave_motor_quantidade' : 'engines',
                       'aeronave_ano_fabricacao' : 'year_manufacturing',
                       'aeronave_assentos' : 'seating',
                       'total_fatalidades' : 'fatalities'}, inplace=True)

### Gravando arquivo CSV

In [40]:
levels.to_csv('/temp/levels.csv', encoding='utf-8', sep=';', index=False)