# Biblioteca Pandas

* ### Biblioteca open source, escrita sobre a NumPy, extremamente eficiente para limpeza e manipulação de grandes quantidades de dados. Trabalha os dados de forma muito semelhante ao MS Excel (linhas e colunas).

* ### Oferece estruturas e funções para facilitar a análise de dados em Python. Originalmente suas funções eram concentradas para análise de séries temporais, porém foi evoluindo e hoje possui suporte para diversos tipos de dados.

* ### Outra grande vantagem é que boa parte do código foi implementada em linguagem C para melhorar a performance. Assim como a biblioteca NumPy buscou-se a facilidade da linguagem Python com a performance similar à da linguagem C.

> ### http://pandas.pydata.org/

### Sua instalação é bastante simples, feita através do PIP ou Conda:

```javascript
pip install pandas      ou      conda install pandas
```

### Neste módulo serão abordados os principais objetos do Pandas:
* #### Series
* #### DataFrames
* #### Agrupamentos (GroupBy)
* #### Entrada e Saída de dados
* #### Dados Faltantes
* #### Concatenação e mesclagem
* #### Operações
---

In [1]:
import numpy as np
import pandas as pd

## Series

### Uma Series é como um array unidimensional, uma lista de valores que sempre tem um índice relacionado, que rotula cada elemento da lista formando uma estrutura semelhando a de um dicionário do Python.

In [3]:
lista = [10, 20, 30]
array = np.array([10, 20, 30])
dic = {'A':10, 'B':20, 'C':30}

In [4]:
my_list = pd.Series(lista)
my_list

0    10
1    20
2    30
dtype: int64

In [9]:
coord = pd.Series(lista, ['X', 'Y', 'Z'])
coord

X    10
Y    20
Z    30
dtype: int64

In [10]:
pd.Series(['X', 'Y', 'Z'], lista)

10    X
20    Y
30    Z
dtype: object

In [11]:
pd.Series(array)

0    10
1    20
2    30
dtype: int32

In [12]:
s = pd.Series(dic)
s

A    10
B    20
C    30
dtype: int64

In [13]:
type(s)

pandas.core.series.Series

### Elementos podem ser acessados através de seu índice:

In [15]:
coord['Y']

20

In [16]:
my_list[0]

10

_**NOTE** que tanto índices quanto valores podem ser de qualquer tipo do Python ou de qualquer biblioteca referenciada_

### Fornece informações estatísticas básicas sobre a série (no caso de séries numéricas)

In [17]:
array = np.random.randint(1, 100, 10)
series = pd.Series(array)
series

0    15
1    95
2    70
3    53
4    86
5    43
6    78
7    28
8    67
9    44
dtype: int32

In [18]:
series.mean()

57.9

In [19]:
series.std()

25.761513068054747

In [20]:
series.min()

15

In [21]:
series.max()

95

In [22]:
series.value_counts()

15    1
78    1
28    1
43    1
70    1
53    1
67    1
95    1
86    1
44    1
dtype: int64

In [23]:
series.describe()

count    10.000000
mean     57.900000
std      25.761513
min      15.000000
25%      43.250000
50%      60.000000
75%      76.000000
max      95.000000
dtype: float64

### Operações com escalares

In [24]:
pd.Series([10, 20, 30, 40, 50]) / 10

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [25]:
pd.Series([10, 20, 30, 40, 50]) * 10

0    100
1    200
2    300
3    400
4    500
dtype: int64

### Operações baseadas em indices:

In [26]:
female_by_uf = pd.Series([1142487, 1185868, 248416, 5509991], ['AL', 'AM', 'AP', 'BA'])

In [27]:
male_by_uf = pd.Series([1004033, 1134335, 239029, 5053946], ['AL', 'AM', 'AP', 'BA'])

In [28]:
total_by_uf = female_by_uf + male_by_uf

In [29]:
total_by_uf

AL     2146520
AM     2320203
AP      487445
BA    10563937
dtype: int64

In [30]:
female_by_uf = pd.Series([71850, 1142487, 1185868, 248416, 5509991], ['AC', 'AL', 'AM', 'AP', 'BA'])

In [31]:
male_by_uf = pd.Series([1004033, 1134335, 239029, 5053946, 2991782, 1301956], ['AL', 'AM', 'AP', 'BA', 'CE', 'ES'])

In [32]:
total_by_uf = female_by_uf + male_by_uf

In [33]:
total_by_uf

AC           NaN
AL     2146520.0
AM     2320203.0
AP      487445.0
BA    10563937.0
CE           NaN
ES           NaN
dtype: float64

## DataFrame

### DataFrame é o principal objeto da biblioteca Pandas. É composto basicamente por conjuntos de Series organizados de forma bidimensional e indexados.

### Pode ser criado de várias formas diferentes:

In [34]:
df = pd.DataFrame([[10, 20, 30], [40, 50 , 60], [70, 80, 90]])
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [102]:
np.random.seed(100)

In [103]:
df = pd.DataFrame(np.random.randn(5, 4))
df

          0         1         2         3
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318

In [63]:
df = pd.DataFrame(np.random.randn(5, 4), index=['A', 'B', 'C', 'D', 'E'])
df

          0         1         2         3
A -1.749765  0.342680  1.153036 -0.252436
B  0.981321  0.514219  0.221180 -1.070043
C -0.189496  0.255001 -0.458027  0.435163
D -0.583595  0.816847  0.672721 -0.104411
E -0.531280  1.029733 -0.438136 -1.118318

In [65]:
df = pd.DataFrame(np.random.randn(5, 4), columns=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318

In [109]:
df = pd.DataFrame(np.random.randn(5, 4), 
                  index=['A', 'B', 'C', 'D', 'E'], 
                  columns=['W', 'X', 'Y', 'Z'])
df

          W         X         Y         Z
A  1.618982  1.541605 -0.251879 -0.842436
B  0.184519  0.937082  0.731000  1.361556
C -0.326238  0.055676  0.222400 -1.443217
D -0.756352  0.816454  0.750445 -0.455947
E  1.189622 -1.690617 -1.356399 -1.232435

### A indexação de um DataFrame é muito semelhante à de utilizadas em dicionários:
**As colunas de um DataFrame são Series**

In [67]:
df['W']

A    1.618982
B    0.184519
C   -0.326238
D   -0.756352
E    1.189622
Name: W, dtype: float64

In [71]:
df[['W', 'Y']]

          W         Y
A  1.618982 -0.251879
B  0.184519  0.731000
C -0.326238  0.222400
D -0.756352  0.750445
E  1.189622 -1.356399

### É possível criar novas colunas apenas atribuindo uma Series a ela:

In [74]:
df['X_Y'] = df['X'] + df['Y']
df

          W         X         Y         Z       X_Y
A -0.544439 -0.668172  0.007315 -0.612939 -0.660857
B  1.299748 -1.733096 -0.983310  0.357508 -2.716406
C -1.613579  1.470714 -1.188018 -0.549746  0.282696
D -0.940046 -0.827932  0.108863  0.507810 -0.719069
E -0.862227  1.249470 -0.079611 -0.889731  1.169858

In [78]:
df['Another'] = [23, 456, 89, -34, 66]
df

          W         X         Y         Z       X_Y  Another
A -0.544439 -0.668172  0.007315 -0.612939 -0.660857       23
B  1.299748 -1.733096 -0.983310  0.357508 -2.716406      456
C -1.613579  1.470714 -1.188018 -0.549746  0.282696       89
D -0.940046 -0.827932  0.108863  0.507810 -0.719069      -34
E -0.862227  1.249470 -0.079611 -0.889731  1.169858       66

In [80]:
df['W']

A   -0.544439
B    1.299748
C   -1.613579
D   -0.940046
E   -0.862227
Name: W, dtype: float64

In [81]:
df.drop('X_Y', axis=1)

          W         X         Y         Z  Another
A -0.544439 -0.668172  0.007315 -0.612939       23
B  1.299748 -1.733096 -0.983310  0.357508      456
C -1.613579  1.470714 -1.188018 -0.549746       89
D -0.940046 -0.827932  0.108863  0.507810      -34
E -0.862227  1.249470 -0.079611 -0.889731       66

In [82]:
df

          W         X         Y         Z       X_Y  Another
A -0.544439 -0.668172  0.007315 -0.612939 -0.660857       23
B  1.299748 -1.733096 -0.983310  0.357508 -2.716406      456
C -1.613579  1.470714 -1.188018 -0.549746  0.282696       89
D -0.940046 -0.827932  0.108863  0.507810 -0.719069      -34
E -0.862227  1.249470 -0.079611 -0.889731  1.169858       66

### Porém esta operação não afeta diretamente o DataFrame, para que isso ocorra é necessário utilizar o parâmetro *inplace*

In [83]:
df.drop('X_Y', axis=1, inplace=True)
df

          W         X         Y         Z  Another
A -0.544439 -0.668172  0.007315 -0.612939       23
B  1.299748 -1.733096 -0.983310  0.357508      456
C -1.613579  1.470714 -1.188018 -0.549746       89
D -0.940046 -0.827932  0.108863  0.507810      -34
E -0.862227  1.249470 -0.079611 -0.889731       66

In [85]:
df = df.drop('Another', axis=1)
df

          W         X         Y         Z
A -0.544439 -0.668172  0.007315 -0.612939
B  1.299748 -1.733096 -0.983310  0.357508
C -1.613579  1.470714 -1.188018 -0.549746
D -0.940046 -0.827932  0.108863  0.507810
E -0.862227  1.249470 -0.079611 -0.889731

### Elementos podem ser localizados usando o método *loc* seguindo a notação de linha X coluna:

In [107]:
df

          0         1         2         3
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318

In [110]:
df.loc['A', 'W']

1.6189816606752596

In [88]:
df.loc['C', 'Y']

-1.1880175973177194

### Quando a coluna é omitida, o retorno serão todos os elementos da linha selecionada em formato Series:

In [92]:
df.loc['A']

W   -0.544439
X   -0.668172
Y    0.007315
Z   -0.612939
Name: A, dtype: float64

In [93]:
df.loc['C']

W   -1.613579
X    1.470714
Y   -1.188018
Z   -0.549746
Name: C, dtype: float64

### A notação linha X coluna também pode ser utilizada:

In [94]:
df.loc[['A', 'C'], ['Y', 'Z']]

          Y         Z
A  0.007315 -0.612939
C -1.188018 -0.549746

### É possivel localizar elementos através de índices numéricos assim como na NumPy através do método *iloc*:

In [95]:
df.iloc[1:4]

          W         X         Y         Z
B  1.299748 -1.733096 -0.983310  0.357508
C -1.613579  1.470714 -1.188018 -0.549746
D -0.940046 -0.827932  0.108863  0.507810

In [96]:
df.iloc[:2, 2:]

          Y         Z
A  0.007315 -0.612939
B -0.983310  0.357508

### De uma forma muito semelhante à seleção condicional do NumPy, com os Dataframes e Series do Pandas é possível localizar elementos baseado em condições além da localização por linhas, colunas ou índices:

In [97]:
df > 0

       W      X      Y      Z
A  False  False   True  False
B   True  False  False   True
C  False   True  False  False
D  False  False   True   True
E  False   True  False  False

In [98]:
df[df > 0]

          W         X         Y         Z
A       NaN       NaN  0.007315       NaN
B  1.299748       NaN       NaN  0.357508
C       NaN  1.470714       NaN       NaN
D       NaN       NaN  0.108863  0.507810
E       NaN  1.249470       NaN       NaN

#### Note que os indices dos elementos que não obedecem ao critério estabelecido, retornam com NaN (Não disponível)

### A partir do DataFrame resultante, é possível fazer operações de *slicing*:

In [111]:
df[df['W'] > 0]

          W         X         Y         Z
A  1.618982  1.541605 -0.251879 -0.842436
B  0.184519  0.937082  0.731000  1.361556
E  1.189622 -1.690617 -1.356399 -1.232435

In [100]:
df[df['W'] > 0][['X', 'Y']]

          X        Y
B -1.733096 -0.98331

In [112]:

df[df['W'] > 0][['X', 'Y']][1:]

          X         Y
B  0.937082  0.731000
E -1.690617 -1.356399

### É possível combinar condições em uma seleção condicional utilizando os operadores & e |

In [114]:
mask1 = df['W'] > 0
df[mask1]

          W         X         Y         Z
A  1.618982  1.541605 -0.251879 -0.842436
B  0.184519  0.937082  0.731000  1.361556
E  1.189622 -1.690617 -1.356399 -1.232435

In [118]:
df[((df['X'] < 0) & (df['Y'] > 0) | (df['Z'] < 0))]

          W         X         Y         Z
A  1.618982  1.541605 -0.251879 -0.842436
C -0.326238  0.055676  0.222400 -1.443217
D -0.756352  0.816454  0.750445 -0.455947
E  1.189622 -1.690617 -1.356399 -1.232435

### É possível reiniciar as condições do índice de um DataFrame através do método *reset_index*:

In [121]:
df.reset_index()

  index         W         X         Y         Z
0     A  1.618982  1.541605 -0.251879 -0.842436
1     B  0.184519  0.937082  0.731000  1.361556
2     C -0.326238  0.055676  0.222400 -1.443217
3     D -0.756352  0.816454  0.750445 -0.455947
4     E  1.189622 -1.690617 -1.356399 -1.232435

### Ou substituir o índice por valores de uma coluna do DataFrame qualquer:

In [122]:
df

          W         X         Y         Z
A  1.618982  1.541605 -0.251879 -0.842436
B  0.184519  0.937082  0.731000  1.361556
C -0.326238  0.055676  0.222400 -1.443217
D -0.756352  0.816454  0.750445 -0.455947
E  1.189622 -1.690617 -1.356399 -1.232435

In [127]:
df['Estados'] = ['SP', 'RJ', 'MG', 'ES', 'SC']

In [129]:
df.set_index('Estados')
df

          W         X         Y         Z Estados
A  1.618982  1.541605 -0.251879 -0.842436      SP
B  0.184519  0.937082  0.731000  1.361556      RJ
C -0.326238  0.055676  0.222400 -1.443217      MG
D -0.756352  0.816454  0.750445 -0.455947      ES
E  1.189622 -1.690617 -1.356399 -1.232435      SC

### Operações de agrupamento podem ser efetuadas através do método *groupby*:

In [130]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df

   Team   Seller  Sale
0  Alfa      Bob   120
1  Beta      Sam   250
2  Alfa  Charlie   180
3  Beta    Smith   100
4  Beta      Sam    95
5  Alfa      Bob   278

In [131]:
by_team = df.groupby(by='Team')
by_team

### Várias informações podem ser extraídas a partir de um *DataFrameGroupBy*

In [132]:
by_team.sum()

      Sale
Team
Alfa   578
Beta   445

In [133]:
by_team.max()

       Seller  Sale
Team
Alfa  Charlie   278
Beta    Smith   250

In [134]:
by_team.min()

     Seller  Sale
Team
Alfa    Bob   120
Beta    Sam    95

In [135]:
by_team.mean()

            Sale
Team
Alfa  192.666667
Beta  148.333333

In [136]:
by_team.std()

           Sale
Team
Alfa  79.757967
Beta  88.081402

### Algumas informações estatísticas podem ser obtidas através do método *describe*

In [137]:
by_seller = df.groupby(by='Seller')
by_seller

In [138]:
by_seller.describe()

         Sale
        count   mean         std    min     25%    50%     75%    max
Seller
Bob       2.0  199.0  111.722871  120.0  159.50  199.0  238.50  278.0
Charlie   1.0  180.0         NaN  180.0  180.00  180.0  180.00  180.0
Sam       2.0  172.5  109.601551   95.0  133.75  172.5  211.25  250.0
Smith     1.0  100.0         NaN  100.0  100.00  100.0  100.00  100.0

### As operações de agrupamento, retornam DataFrames que podem ser fatiados:

In [140]:
s = by_seller.sum()
s

         Sale
Seller
Bob       398
Charlie   180
Sam       345
Smith     100

In [141]:
s.loc['Bob']

Sale    398
Name: Bob, dtype: int64

In [142]:
s[s['Sale'] > 200]

        Sale
Seller
Bob      398
Sam      345

### Pandas fornece uma série de métodos para entrada e saída de dados. Basicamente em uma operação é possível ler um conjunto de dados de uma determinada fonte de forma que sejam já disponibilizadas em um DataFrame.

### Para isso é necessário conhecer o tipo e as características da fonte de dados, por exemplo, um arquivo CSV, seu separador e encoding. Os métodos *read_\** e *to_\** fornecem o suporte necessário para tal tarefa:

In [152]:
df = pd.read_csv('/temp/heroes.csv')sim
df.head()

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0

In [153]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df.to_csv('/temp/sales.csv')
df.to_json('/temp/sales.json')
df.to_clipboard()