In [163]:
import pandas as pd
import tensorflow as tf
%matplotlib inline
from sklearn.model_selection import train_test_split

In [243]:
base = pd.read_csv('breast-cancer.csv',encoding='UTF-8')
base.head()

,code_number,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epitelial_cell_size,bare_nuclei,bland_chromation,normal_nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,benign
1,1002945,5,4,4,5,7,10,3,2,1,benign
2,1015425,3,1,1,1,2,2,3,1,1,benign
3,1016277,6,8,8,1,3,4,3,7,1,benign
4,1017023,4,1,1,3,2,1,3,1,1,benign

In [244]:
base['class'].unique()

array(['benign', 'malignant'], dtype=object)

In [195]:
base.shape

(699, 11)

In [196]:
def convert_class(rotulo):
    if rotulo == 'benign':
        return 1
    else:
        return 0

In [197]:
base['bare_nuclei'].unique()

array(['1', '10', '2', '4', '3', '9', '7', '?', '5', '8', '6'],
      dtype=object)

In [198]:
base['bare_nuclei'].replace('?', '0' ,inplace=True)
base['bare_nuclei'].unique()

array(['1', '10', '2', '4', '3', '9', '7', '0', '5', '8', '6'],
      dtype=object)

In [199]:
base['class'] = base['class'].apply(convert_class)

In [200]:
base.head()

,code_number,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epitelial_cell_size,bare_nuclei,bland_chromation,normal_nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,1
1,1002945,5,4,4,5,7,10,3,2,1,1
2,1015425,3,1,1,1,2,2,3,1,1,1
3,1016277,6,8,8,1,3,4,3,7,1,1
4,1017023,4,1,1,3,2,1,3,1,1,1

In [201]:
X = base.drop(['class','code_number'], axis = 1)
X.head()

,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epitelial_cell_size,bare_nuclei,bland_chromation,normal_nucleoli,mitoses
0,5,1,1,1,2,1,3,1,1
1,5,4,4,5,7,10,3,2,1
2,3,1,1,1,2,2,3,1,1
3,6,8,8,1,3,4,3,7,1
4,4,1,1,3,2,1,3,1,1

In [202]:
y = base['class']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [203]:
X.columns

Index(['clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape',
       'marginal_adhesion', 'single_epitelial_cell_size', 'bare_nuclei',
       'bland_chromation', 'normal_nucleoli', 'mitoses'],
      dtype='object')

In [204]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [205]:
X_treinamento.shape

(489, 9)

In [206]:
X_teste.shape

(210, 9)

In [207]:
nome_colunas_numericas = ['clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape', 'marginal_adhesion', 'single_epitelial_cell_size','bare_nuclei','bland_chromation','normal_nucleoli','mitoses']
nome_colunas_numericas

['clump_thickness',
 'uniformity_cell_size',
 'uniformity_cell_shape',
 'marginal_adhesion',
 'single_epitelial_cell_size',
 'bare_nuclei',
 'bland_chromation',
 'normal_nucleoli',
 'mitoses']

In [208]:
colunas_numericas = [ tf.feature_column.numeric_column(key = c) for c in nome_colunas_numericas ]
colunas_numericas

[_NumericColumn(key='clump_thickness', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='uniformity_cell_size', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='uniformity_cell_shape', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='marginal_adhesion', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='single_epitelial_cell_size', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='bare_nuclei', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='bland_chromation', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='normal_nucleoli', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='mitoses', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [209]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [210]:
classificador = tf.estimator.LinearClassifier(feature_columns=colunas_numericas)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\183134\AppData\Local\Temp\tmpc9o_elkz
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\183134\\AppData\\Local\\Temp\\tmpc9o_elkz', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000023A3DDB1DA0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [211]:
classificador.train(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\183134\AppData\Local\Temp\tmpc9o_elkz\model.ckpt.

UnimplementedError: Cast string to float is not supported
	 [[node linear/linear_model/linear_model/bare_nuclei/ToFloat (defined at <ipython-input-211-394586062caa>:1)  = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](linear/linear_model/linear_model/bare_nuclei/ExpandDims)]]

Caused by op 'linear/linear_model/linear_model/bare_nuclei/ToFloat', defined at:
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 3191, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-211-394586062caa>", line 1, in <module>
    classificador.train(input_fn=funcao_treinamento, steps = 10000)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 384, in _model_fn
    sparse_combiner=sparse_combiner)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 208, in _linear_model_fn
    logits = logit_fn(features=features)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 143, in linear_logit_fn
    logits = linear_model(features)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 673, in call
    weighted_sum = layer(builder)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\layers\base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 565, in call
    weight_var=self._weight_var)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2056, in _create_weighted_sum
    weight_var=weight_var)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2069, in _create_dense_column_weighted_sum
    trainable=trainable)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2500, in _get_dense_tensor
    return inputs.get(self)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2289, in get
    transformed = column._transform_feature(self)  # pylint: disable=protected-access
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2475, in _transform_feature
    return math_ops.to_float(input_tensor)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 732, in to_float
    return cast(x, dtypes.float32, name=name)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 677, in cast
    x = gen_math_ops.cast(x, base_type, name=name)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1658, in cast
    "Cast", x=x, DstT=DstT, Truncate=Truncate, name=name)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnimplementedError (see above for traceback): Cast string to float is not supported
	 [[node linear/linear_model/linear_model/bare_nuclei/ToFloat (defined at <ipython-input-211-394586062caa>:1)  = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](linear/linear_model/linear_model/bare_nuclei/ExpandDims)]]

In [ ]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, batch_size = 32, shuffle = False)

In [ ]:
previsoes = classificador.predict(input_fn=funcao_previsao)

In [67]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\183134\AppData\Local\Temp\tmp7_lw80gt\model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

UnimplementedError: Cast string to float is not supported
	 [[node linear/linear_model/linear_model/bare_nuclei/ToFloat (defined at <ipython-input-67-779e69f3eef5>:1)  = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](linear/linear_model/linear_model/bare_nuclei/ExpandDims)]]

Caused by op 'linear/linear_model/linear_model/bare_nuclei/ToFloat', defined at:
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 3191, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-67-779e69f3eef5>", line 1, in <module>
    list(previsoes)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 577, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 384, in _model_fn
    sparse_combiner=sparse_combiner)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 208, in _linear_model_fn
    logits = logit_fn(features=features)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 143, in linear_logit_fn
    logits = linear_model(features)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 673, in call
    weighted_sum = layer(builder)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\layers\base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 565, in call
    weight_var=self._weight_var)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2056, in _create_weighted_sum
    weight_var=weight_var)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2069, in _create_dense_column_weighted_sum
    trainable=trainable)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2500, in _get_dense_tensor
    return inputs.get(self)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2289, in get
    transformed = column._transform_feature(self)  # pylint: disable=protected-access
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2475, in _transform_feature
    return math_ops.to_float(input_tensor)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 732, in to_float
    return cast(x, dtypes.float32, name=name)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 677, in cast
    x = gen_math_ops.cast(x, base_type, name=name)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1658, in cast
    "Cast", x=x, DstT=DstT, Truncate=Truncate, name=name)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnimplementedError (see above for traceback): Cast string to float is not supported
	 [[node linear/linear_model/linear_model/bare_nuclei/ToFloat (defined at <ipython-input-67-779e69f3eef5>:1)  = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](linear/linear_model/linear_model/bare_nuclei/ExpandDims)]]