# Biblioteca Pandas (Créditos ao Professor Luciano Nunes)

* Biblioteca open source, escrita sobre a NumPy, extremamente eficiente para limpeza e manipulação de grandes quantidades de dados. Trabalha os dados de forma muito semelhante ao MS Excel (linhas e colunas).

* Oferece estruturas e funções para facilitar a análise de dados em Python. Originalmente suas funções eram concentradas para análise de séries temporais, porém foi evoluindo e hoje possui suporte para diversos tipos de dados.

* Outra grande vantagem é que boa parte do código foi implementada em linguagem C para melhorar a performance. Assim como a biblioteca NumPy buscou-se a facilidade da linguagem Python com a performance similar à da linguagem C.

>  http://pandas.pydata.org/

### Sua instalação é bastante simples, feita através do PIP ou Conda:

```bash
pip install pandas      ou      conda install pandas
```

### Neste módulo serão abordados os principais objetos do Pandas:
* Series
* DataFrames
* Agrupamentos (GroupBy)
* Entrada e Saída de dados
* Índices Multiníveis
* Dados Faltantes
* Concatenação e mesclagem

In [2]:
import numpy as np
import pandas as pd

## Series

### Uma Series é como um array unidimensional, uma lista de valores que sempre tem um índice relacionado, que rotula cada elemento da lista formando uma estrutura semelhando a de um dicionário do Python.

In [3]:
lista = [10, 20, 30]
array = np.array([10, 20, 30])
dic = {'A':10, 'B':20, 'C':30}

In [4]:
my_list = pd.Series(lista)
my_list

0    10
1    20
2    30
dtype: int64

In [4]:
coord = pd.Series(lista, ['X', 'Y', 'Z'])
coord

X    10
Y    20
Z    30
dtype: int64

In [5]:
pd.Series(['X', 'Y', 'Z'], lista)

10    X
20    Y
30    Z
dtype: str

In [6]:
pd.Series(array)

0    10
1    20
2    30
dtype: int64

In [7]:
s = pd.Series(dic)
s

A    10
B    20
C    30
dtype: int64

In [8]:
type(s)

pandas.Series

### Elementos podem ser acessados através de seu índice:

In [9]:
coord['Y']

np.int64(20)

In [10]:
my_list[0]

np.int64(10)

_**NOTE** que tanto índices quanto valores podem ser de qualquer tipo do Python ou de qualquer biblioteca referenciada_

### Fornece informações estatísticas básicas sobre a série (no caso de séries numéricas)

In [11]:
array = np.random.randint(1, 100, 10)
series = pd.Series(array)
series

0    91
1    99
2    49
3    83
4    56
5    25
6    77
7    76
8    27
9    51
dtype: int32

In [12]:
series.mean()

np.float64(63.4)

In [13]:
series.std()

np.float64(25.760434778939583)

In [14]:
series.min()

np.int32(25)

In [15]:
series.max()

np.int32(99)

In [16]:
series.value_counts()

91    1
99    1
49    1
83    1
56    1
25    1
77    1
76    1
27    1
51    1
Name: count, dtype: int64

In [17]:
series.describe()

count    10.000000
mean     63.400000
std      25.760435
min      25.000000
25%      49.500000
50%      66.000000
75%      81.500000
max      99.000000
dtype: float64

### Operações com escalares

In [18]:
pd.Series([10, 20, 30, 40, 50]) / 10

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [19]:
pd.Series([10, 20, 30, 40, 50]) * 10

0    100
1    200
2    300
3    400
4    500
dtype: int64

### Operações baseadas em indices:

In [20]:
female_by_uf = pd.Series([1142487, 1185868, 248416, 5509991], ['AL', 'AM', 'AP', 'BA'])

In [21]:
male_by_uf = pd.Series([1004033, 1134335, 239029, 5053946], ['AL', 'AM', 'AP', 'BA'])

In [22]:
total_by_uf = female_by_uf + male_by_uf

In [23]:
total_by_uf

AL     2146520
AM     2320203
AP      487445
BA    10563937
dtype: int64

In [24]:
female_by_uf = pd.Series([71850,   1142487, 1185868, 248416,  5509991         ], ['AC', 'AL', 'AM', 'AP', 'BA'])

In [25]:
male_by_uf = pd.Series(  [1004033, 1134335, 239029,  5053946, 2991782, 1301956], ['AL', 'AM', 'AP', 'BA', 'CE', 'ES'])

In [26]:
total_by_uf = female_by_uf + male_by_uf

In [27]:
total_by_uf

AC           NaN
AL     2146520.0
AM     2320203.0
AP      487445.0
BA    10563937.0
CE           NaN
ES           NaN
dtype: float64

## DataFrame

### DataFrame é o principal objeto da biblioteca Pandas. É composto basicamente por conjuntos de Series organizados de forma bidimensional e indexados.

### Pode ser criado de várias formas diferentes:

In [28]:
df = pd.DataFrame([[10, 20, 30], [40, 50 , 60], [70, 80, 90]])
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [29]:
np.random.seed(100)

In [30]:
df = pd.DataFrame(np.random.randn(3, 4))
df

          0         1         2         3
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163

In [31]:
df = pd.DataFrame(np.random.randn(5, 4), index=['A', 'B', 'C', 'D', 'E'])
df

          0         1         2         3
A -0.583595  0.816847  0.672721 -0.104411
B -0.531280  1.029733 -0.438136 -1.118318
C  1.618982  1.541605 -0.251879 -0.842436
D  0.184519  0.937082  0.731000  1.361556
E -0.326238  0.055676  0.222400 -1.443217

In [32]:
df = pd.DataFrame(np.random.randn(5, 4), columns=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0 -0.756352  0.816454  0.750445 -0.455947
1  1.189622 -1.690617 -1.356399 -1.232435
2 -0.544439 -0.668172  0.007315 -0.612939
3  1.299748 -1.733096 -0.983310  0.357508
4 -1.613579  1.470714 -1.188018 -0.549746

In [33]:
df = pd.DataFrame(np.random.randn(5, 4), 
                  index=['A', 'B', 'C', 'D', 'E'], 
                  columns=['W', 'X', 'Y', 'Z'])
df

          W         X         Y         Z
A -0.940046 -0.827932  0.108863  0.507810
B -0.862227  1.249470 -0.079611 -0.889731
C -0.881798  0.018639  0.237845  0.013549
D -1.635529 -1.044210  0.613039  0.736205
E  1.026921 -1.432191 -1.841188  0.366093

### A indexação de um DataFrame é muito semelhante à de utilizadas em dicionários:
**As colunas de um DataFrame são Series**

In [34]:
df['W']

A   -0.940046
B   -0.862227
C   -0.881798
D   -1.635529
E    1.026921
Name: W, dtype: float64

In [35]:
df[['W', 'Y']]

          W         Y
A -0.940046  0.108863
B -0.862227 -0.079611
C -0.881798  0.237845
D -1.635529  0.613039
E  1.026921 -1.841188

### É possível criar novas colunas apenas atribuindo uma Series a ela:

In [36]:
df['X_Y'] = df['X'] + df['Y']
df

          W         X         Y         Z       X_Y
A -0.940046 -0.827932  0.108863  0.507810 -0.719069
B -0.862227  1.249470 -0.079611 -0.889731  1.169858
C -0.881798  0.018639  0.237845  0.013549  0.256484
D -1.635529 -1.044210  0.613039  0.736205 -0.431171
E  1.026921 -1.432191 -1.841188  0.366093 -3.273379

In [37]:
df['Another'] = [23, 456, 89, -34, 66]
df

          W         X         Y         Z       X_Y  Another
A -0.940046 -0.827932  0.108863  0.507810 -0.719069       23
B -0.862227  1.249470 -0.079611 -0.889731  1.169858      456
C -0.881798  0.018639  0.237845  0.013549  0.256484       89
D -1.635529 -1.044210  0.613039  0.736205 -0.431171      -34
E  1.026921 -1.432191 -1.841188  0.366093 -3.273379       66

In [38]:
df['W']

A   -0.940046
B   -0.862227
C   -0.881798
D   -1.635529
E    1.026921
Name: W, dtype: float64

In [39]:
df.drop('X_Y', axis=1)

          W         X         Y         Z  Another
A -0.940046 -0.827932  0.108863  0.507810       23
B -0.862227  1.249470 -0.079611 -0.889731      456
C -0.881798  0.018639  0.237845  0.013549       89
D -1.635529 -1.044210  0.613039  0.736205      -34
E  1.026921 -1.432191 -1.841188  0.366093       66

In [40]:
df

          W         X         Y         Z       X_Y  Another
A -0.940046 -0.827932  0.108863  0.507810 -0.719069       23
B -0.862227  1.249470 -0.079611 -0.889731  1.169858      456
C -0.881798  0.018639  0.237845  0.013549  0.256484       89
D -1.635529 -1.044210  0.613039  0.736205 -0.431171      -34
E  1.026921 -1.432191 -1.841188  0.366093 -3.273379       66

### Porém esta operação não afeta diretamente o DataFrame, para que isso ocorra é necessário utilizar o parâmetro *inplace*

In [41]:
df.drop('X_Y', axis=1, inplace=True)
df

          W         X         Y         Z  Another
A -0.940046 -0.827932  0.108863  0.507810       23
B -0.862227  1.249470 -0.079611 -0.889731      456
C -0.881798  0.018639  0.237845  0.013549       89
D -1.635529 -1.044210  0.613039  0.736205      -34
E  1.026921 -1.432191 -1.841188  0.366093       66

In [42]:
df = df.drop('Another', axis=1)
df

          W         X         Y         Z
A -0.940046 -0.827932  0.108863  0.507810
B -0.862227  1.249470 -0.079611 -0.889731
C -0.881798  0.018639  0.237845  0.013549
D -1.635529 -1.044210  0.613039  0.736205
E  1.026921 -1.432191 -1.841188  0.366093

### Elementos podem ser localizados usando o método *loc* seguindo a notação de linha X coluna:

In [43]:
df

          W         X         Y         Z
A -0.940046 -0.827932  0.108863  0.507810
B -0.862227  1.249470 -0.079611 -0.889731
C -0.881798  0.018639  0.237845  0.013549
D -1.635529 -1.044210  0.613039  0.736205
E  1.026921 -1.432191 -1.841188  0.366093

In [44]:
df.loc['A', 'W']

np.float64(-0.9400461615447682)

In [45]:
df.loc['C', 'Y']

np.float64(0.2378446219236218)

### Quando a coluna é omitida, o retorno serão todos os elementos da linha selecionada em formato Series:

In [46]:
df.loc['A']

W   -0.940046
X   -0.827932
Y    0.108863
Z    0.507810
Name: A, dtype: float64

In [47]:
df.loc['C']

W   -0.881798
X    0.018639
Y    0.237845
Z    0.013549
Name: C, dtype: float64

### A notação linha X coluna também pode ser utilizada:

In [48]:
df.loc[['A', 'C'], ['Y', 'Z']]

          Y         Z
A  0.108863  0.507810
C  0.237845  0.013549

### É possivel localizar elementos através de índices numéricos assim como na NumPy através do método *iloc*:

In [49]:
df.iloc[1:4]

          W         X         Y         Z
B -0.862227  1.249470 -0.079611 -0.889731
C -0.881798  0.018639  0.237845  0.013549
D -1.635529 -1.044210  0.613039  0.736205

In [50]:
df.iloc[:2, 2:]

          Y         Z
A  0.108863  0.507810
B -0.079611 -0.889731

### De uma forma muito semelhante à seleção condicional do NumPy, com os Dataframes e Series do Pandas é possível localizar elementos baseado em condições além da localização por linhas, colunas ou índices:

In [51]:
df > 0

       W      X      Y      Z
A  False  False   True   True
B  False   True  False  False
C  False   True   True   True
D  False  False   True   True
E   True  False  False   True

In [52]:
df[df > 0]

          W         X         Y         Z
A       NaN       NaN  0.108863  0.507810
B       NaN  1.249470       NaN       NaN
C       NaN  0.018639  0.237845  0.013549
D       NaN       NaN  0.613039  0.736205
E  1.026921       NaN       NaN  0.366093

#### Note que os indices dos elementos que não obedecem ao critério estabelecido, retornam com NaN (Não disponível)

### A partir do DataFrame resultante, é possível fazer operações de *slicing*:

In [53]:
df[df['W'] > 0]

          W         X         Y         Z
E  1.026921 -1.432191 -1.841188  0.366093

In [54]:
df[df['W'] > 0][['X', 'Y']]

          X         Y
E -1.432191 -1.841188

In [55]:

df[df['W'] > 0][['X', 'Y']][1:]

Empty DataFrame
Columns: [X, Y]
Index: []

### É possível combinar condições em uma seleção condicional utilizando os operadores & e |

In [56]:
mask1 = df['W'] > 0
df[mask1]

          W         X         Y         Z
E  1.026921 -1.432191 -1.841188  0.366093

In [57]:
df[((df['X'] < 0) & (df['Y'] > 0) | (df['Z'] < 0))]

          W         X         Y         Z
A -0.940046 -0.827932  0.108863  0.507810
B -0.862227  1.249470 -0.079611 -0.889731
D -1.635529 -1.044210  0.613039  0.736205

### É possível reiniciar as condições do índice de um DataFrame através do método *reset_index*:

In [58]:
df.reset_index()

  index         W         X         Y         Z
0     A -0.940046 -0.827932  0.108863  0.507810
1     B -0.862227  1.249470 -0.079611 -0.889731
2     C -0.881798  0.018639  0.237845  0.013549
3     D -1.635529 -1.044210  0.613039  0.736205
4     E  1.026921 -1.432191 -1.841188  0.366093

### Ou substituir o índice por valores de uma coluna do DataFrame qualquer:

In [59]:
df

          W         X         Y         Z
A -0.940046 -0.827932  0.108863  0.507810
B -0.862227  1.249470 -0.079611 -0.889731
C -0.881798  0.018639  0.237845  0.013549
D -1.635529 -1.044210  0.613039  0.736205
E  1.026921 -1.432191 -1.841188  0.366093

In [60]:
df['Estados'] = ['SP', 'RJ', 'MG', 'ES', 'SC']

In [61]:
df.set_index('Estados')
df

          W         X         Y         Z Estados
A -0.940046 -0.827932  0.108863  0.507810      SP
B -0.862227  1.249470 -0.079611 -0.889731      RJ
C -0.881798  0.018639  0.237845  0.013549      MG
D -1.635529 -1.044210  0.613039  0.736205      ES
E  1.026921 -1.432191 -1.841188  0.366093      SC

### Operações de agrupamento podem ser efetuadas através do método *groupby*:

In [62]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df

   Team   Seller  Sale
0  Alfa      Bob   120
1  Beta      Sam   250
2  Alfa  Charlie   180
3  Beta    Smith   100
4  Beta      Sam    95
5  Alfa      Bob   278

In [63]:
by_team = df.groupby(by='Team')
by_team

In [64]:
df.index

RangeIndex(start=0, stop=6, step=1)

### Várias informações podem ser extraídas a partir de um *DataFrameGroupBy*

In [65]:
by_team.sum()

             Seller  Sale
Team
Alfa  BobCharlieBob   578
Beta    SamSmithSam   445

In [66]:
by_team.max()

       Seller  Sale
Team
Alfa  Charlie   278
Beta    Smith   250

In [69]:
by_team.min()

     Seller  Sale
Team
Alfa    Bob   120
Beta    Sam    95

In [70]:
by_team.mean()

TypeError: dtype 'str' does not support operation 'mean'

In [71]:
by_team.std()

TypeError: dtype 'str' does not support operation 'std'

### Algumas informações estatísticas podem ser obtidas através do método *describe*

In [72]:
by_seller = df.groupby(by='Seller')
by_seller

In [73]:
by_seller.describe()

         Sale
        count   mean         std    min     25%    50%     75%    max
Seller
Bob       2.0  199.0  111.722871  120.0  159.50  199.0  238.50  278.0
Charlie   1.0  180.0         NaN  180.0  180.00  180.0  180.00  180.0
Sam       2.0  172.5  109.601551   95.0  133.75  172.5  211.25  250.0
Smith     1.0  100.0         NaN  100.0  100.00  100.0  100.00  100.0

### As operações de agrupamento, retornam DataFrames que podem ser fatiados:

In [74]:
s = by_seller.sum()
s

             Team  Sale
Seller
Bob      AlfaAlfa   398
Charlie      Alfa   180
Sam      BetaBeta   345
Smith        Beta   100

In [75]:
s.loc['Bob']

Team    AlfaAlfa
Sale         398
Name: Bob, dtype: object

In [76]:
s[s['Sale'] > 200]

            Team  Sale
Seller
Bob     AlfaAlfa   398
Sam     BetaBeta   345

### Pandas fornece uma série de métodos para entrada e saída de dados. Basicamente em uma operação é possível ler um conjunto de dados de uma determinada fonte de forma que sejam já disponibilizadas em um DataFrame.

### Para isso é necessário conhecer o tipo e as características da fonte de dados, por exemplo, um arquivo CSV, seu separador e encoding. Os métodos *read_\** e *to_\** fornecem o suporte necessário para tal tarefa:

In [77]:
df = pd.read_csv('../../resources/datasets/heroes.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../../resources/datasets/heroes.csv'

In [78]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df.to_csv('../../resources/datasets/sales.csv')
df.to_json('../../resources/datasets/sales.json')

OSError: Cannot save file into a non-existent directory: '..\..\resources\datasets'

## Índices Multiníveis

In [79]:
groups = [('Grupo 1', 'Sub_1'), 
          ('Grupo 1', 'Sub_2'), 
          ('Grupo 1', 'Sub_3'),
          ('Grupo 2', 'Sub_1'), 
          ('Grupo 2', 'Sub_2'), 
          ('Grupo 2', 'Sub_3')]
groups

[('Grupo 1', 'Sub_1'),
 ('Grupo 1', 'Sub_2'),
 ('Grupo 1', 'Sub_3'),
 ('Grupo 2', 'Sub_1'),
 ('Grupo 2', 'Sub_2'),
 ('Grupo 2', 'Sub_3')]

In [80]:
i = pd.MultiIndex.from_tuples(groups)
i

MultiIndex([('Grupo 1', 'Sub_1'),
            ('Grupo 1', 'Sub_2'),
            ('Grupo 1', 'Sub_3'),
            ('Grupo 2', 'Sub_1'),
            ('Grupo 2', 'Sub_2'),
            ('Grupo 2', 'Sub_3')],
           )

In [81]:
import pandas as pd
import numpy as np

In [82]:
df = pd.DataFrame(np.random.rand(6, 2), index=i, columns=['C1', 'C2'])
df

                     C1        C2
Grupo 1 Sub_1  0.110788  0.312640
        Sub_2  0.456979  0.658940
        Sub_3  0.254258  0.641101
Grupo 2 Sub_1  0.200124  0.657625
        Sub_2  0.778289  0.779598
        Sub_3  0.610328  0.309000

In [ ]:
df.index.names = ['Grupo', 'SubGrupo']
df

In [ ]:
g1 = df.loc['Grupo 1']
g1

In [ ]:
g1['C1']

In [ ]:
g1.loc['Sub_1']

In [ ]:
df.xs(key='Sub_1', level=1)

In [ ]:
df.xs(key='Grupo 1', level=0)

In [ ]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df

In [ ]:
df = df.groupby(by=['Team', 'Seller']).sum()
df

In [ ]:
df.index

In [ ]:
df.xs(key='Bob', level=1)

In [ ]:
df.xs(key='Beta', level=0)

## Dados Faltantes

Eventualmente poderá ocorrer uma situação onde o conjunto de informações fornecido tenha alguns _gaps_, algumas informações que não foram forneceidas em meio a muitas outras fornecidas, e esses "buracos" podem atrapalhar a análise do _DataSet_ pois as operações estatísticas básicas acabam não funcionando de forma adequada.

O Pandas oferece algumas funcionalidades para contornar esses problemas e a utilização desses métodos irá depender do comportamento esperado do tratamento desses dados:

### Método: dropna()
Este método excluirá (_drop_), dependendo dos parâmetros de entrada, linhas ou colunas com dados faltantes.

In [5]:
df = pd.DataFrame({'A':[1, 2, 3], 'B':[np.nan, 4, 5], 'C':[np.nan, 7, np.nan]})
df

   A    B    C
0  1  NaN  NaN
1  2  4.0  7.0
2  3  5.0  NaN

In [6]:
df.dropna()

   A    B    C
1  2  4.0  7.0

In [85]:
df.dropna(axis=1)

   A
0  1
1  2
2  3

In [86]:
df.dropna(axis=1, thresh=2)

   A    B
0  1  NaN
1  2  4.0
2  3  5.0

### Método: fillna()
O método _fillna()_ irá preencher os dados faltantes com critérios passados nos argumentos.

In [87]:
df.fillna(0)

   A    B    C
0  1  0.0  0.0
1  2  4.0  7.0
2  3  5.0  0.0

In [88]:
df.fillna(df.mean())

   A    B    C
0  1  4.5  7.0
1  2  4.0  7.0
2  3  5.0  7.0

In [89]:
df.fillna(df.min())

   A    B    C
0  1  4.0  7.0
1  2  4.0  7.0
2  3  5.0  7.0

In [90]:
df.fillna(df.max())

   A    B    C
0  1  5.0  7.0
1  2  4.0  7.0
2  3  5.0  7.0

In [7]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, 3, np.nan, 4]],
                  columns=list('ABCD'))
df

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
3  NaN  3.0 NaN  4

In [8]:
df.fillna(method='ffill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [93]:
df.fillna(value={'A': 0, 'B': 99, 'C': -1, 'D': 'A'})

     A     B    C  D
0  0.0   2.0 -1.0  0
1  3.0   4.0 -1.0  1
2  0.0  99.0 -1.0  5
3  0.0   3.0 -1.0  4

In [94]:
df.fillna(value={'A': 0, 'B': 99, 'C': -1, 'D': 'A'}, limit=1)

     A     B    C  D
0  0.0   2.0 -1.0  0
1  3.0   4.0  NaN  1
2  NaN  99.0  NaN  5
3  NaN   3.0  NaN  4

### Método: replace()
O método replace substitui um valor por outro passados como argumentos, podendo aceitar escalares, cadeias de caracteres, listas e expressões regulares.

In [95]:
s = pd.Series([0, 1, 2, 3, 4])
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
s.replace(0, 5)

In [ ]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df

In [ ]:
df.replace(0, 5)

In [ ]:
df.replace([0, 1, 2, 3, 7], -1)

In [ ]:
df.replace([0, 1, 2, 3], [4, 3, 2, 1])

In [ ]:
x = df.replace([0, 1, 2, 3], np.nan)
x

In [ ]:
x.replace(np.nan, -1)

In [ ]:
df.replace([1, 2], method='bfill')

In [ ]:
df.replace({0: 10, 1: 'A', 'c': 'Python'})

In [ ]:
df.replace({'A': 0, 'B': 8}, 100)

## Concatenação, junção e mesclagem
Existem 3 formas diferentes de combinar DataFramas do Pandas: _Merging_, _Joining_ e _Concatenating_. Em todas elas o objetivo é o mesmo, trazer informações de DataFrames dispersos para um único DataFrame, com o objetivo de facilitar a análise dos dados.

https://pandas.pydata.org/pandas-docs/stable/merging.html

## Método: concat()

In [97]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']}) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']})

In [98]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [99]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [100]:
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [101]:
pd.concat([df1, df2, df3])

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [102]:
pd.concat([df1, df2, df3], ignore_index=True)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [103]:
pd.concat([df1, df2, df3], axis=1)

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [104]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11'], 
                        'F': ['F1', 'F2', 'F3', 'D11']})

In [105]:
df3

     A    B    C    D    F
0   A8   B8   C8   D8   F1
1   A9   B9   C9   D9   F2
2  A10  B10  C10  D10   F3
3  A11  B11  C11  D11  D11

In [106]:
pd.concat([df1, df2, df3], sort=False)

     A    B    C    D    F
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
0   A4   B4   C4   D4  NaN
1   A5   B5   C5   D5  NaN
2   A6   B6   C6   D6  NaN
3   A7   B7   C7   D7  NaN
0   A8   B8   C8   D8   F1
1   A9   B9   C9   D9   F2
2  A10  B10  C10  D10   F3
3  A11  B11  C11  D11  D11

In [107]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                     index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

In [108]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [109]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [110]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [111]:
pd.concat([df1, df2, df3], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

### Método: merge()

In [112]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                       'A': ['A0', 'A1', 'A2', 'A3'],
                       'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})

In [113]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [114]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [115]:
pd.merge(left, right, on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [116]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                         'C': ['C0', 'C1', 'C2', 'C3'],
                         'D': ['D0', 'D1', 'D2', 'D3']})

In [117]:
left

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [118]:
right

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [119]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [120]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [121]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [122]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

### Método: join()

In [123]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                     index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                     index=['K0', 'K2', 'K3'])

In [124]:
left

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [125]:
right

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [126]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [127]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [128]:
left.join(right, how='left')

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [129]:
left.join(right, how='right')

      A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3